FROM confluentinc/cp-kafka-connect-base:6.1.0

RUN confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:latest && confluent-hub install --no-prompt hpgrahsl/kafka-connect-mongodb:latest && confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:latest